services:
  ibk-manager-backendi:
    container_name: ibk-manager-backend
    image: ibk-manager-backend:latest  # 직접 빌드한 이미지 사용
    ports:
      - "3005:3005"
    networks:
      - ibk-network
    environment:
      - PORT=3005
      - DB_HOST=postgres_postgresql-master_1
      - DB_NAME=ibk_db
      - DB_USER=ibk-manager
      - DB_PASSWORD=fingerai2024!
      - DB_PORT=5432
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ibk-manager:fingerai2024!@postgres_postgresql-master_1/ibk_db

networks:
  ibk-network:
    external: true
