version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 